### ISSUE TITLE
scripts refuse to spawn with .opt/SVC_OPTIONS defaults under s6

### ISSUE THREAD

**Issue by grknight** [tokiclover/supervision-scripts#1]
You currently have ${PRE_OPTS:=-P} in SVC_OPTIONS.  Since s6 does not have a PRE_CMD, this executes `-P ${SVC_CMD}` and does not allow services to start.

**Comment by tokiclover** [comment]
This is a non _issue_ because the default is... to use Runit. Unless you want to discuss the dfault, open an issue then. (So, closing this one.)

Maybe this should be stated more clearly than it is in the README and the comment just above those lines.

However, nothing is decided yet for the form of the documentation. I may clean up the README file to document a bit more the internal... or else clean it for a man (1) or (8) page. Leaving it [the doc] for now.

**Comment by tokiclover** [comment]
Ah... maybe setting two sets of default for Runit/S6 can be done! This is actually easy to do with... SV_OPT=runit|s6... Well, reopening then. Comments?
